### PR TITLE
[PREVIEW] PRO-3371: Fixed IHT values accuracy.

### PR DESCRIPTION
**Pull request by dhruvpatel20**
### Change description ###
Keep the IHT values as BigDecimal, so Java doesn't try to round or use powers of 10 when the numbers are large eg. 999999999.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by davejones74** [comment]
HI @dhruvpatel20 looks good to me, only considerations would be (but I think its fine!!)
1. Do we need 2DP precision - I imagine not!
2. Should we round up just in case I.e. .setScale(0, RoundingMode.HALF_UP).

**Comment by dhruvpatel20** [comment]
@davejones74 Values are always converted into pennies, so will always be .00, so rounding won't matter

**Comment by venumadhavancha** [comment]
This is for next sprint, please do not merge.

**Comment by dhruvpatel20** [comment]
Preview is not showing, therefore creating a new pull request.

**Pull request closed without merging**
